/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visitormanagementsystem;

import java.awt.*;
import java.sql.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author justi
 */
public class ElderlyUpdate extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    ImageIcon logo = new ImageIcon("C:\\Users\\justi\\Desktop\\Programming\\Java\\VisitorManagementSystem\\src\\assets\\SJCF_LOGO.png");
    
    public ElderlyUpdate() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        elderlyLastTextField.setFocusable(false);
        elderlyFirstTextField.setFocusable(false);
        elderlyMiddleTextField.setFocusable(false);
        elderlySuffix.setFocusable(false);
        elderlyGender.setFocusable(false);
        elderlyBirthdate.setFocusable(false);
        elderlyContact.setFocusable(false);
        elderlyGuardian.setFocusable(false);
        elderlyStreet.setFocusable(false);
        elderlyBrgy.setFocusable(false);
        elderlyCity.setFocusable(false);
        elderlyProvince.setFocusable(false);
        elderlyAdmitDate.setFocusable(false);
        elderlyRoomNo.setFocusable(false);
        elderlyAttendantID.setFocusable(false);
        elderlyID.setFocusable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizeLogo = new javax.swing.JLabel();
        elderlyInformationText = new javax.swing.JLabel();
        personalInfoBG = new javax.swing.JPanel();
        elderlyBirthdateText = new javax.swing.JLabel();
        elderlyLastTextField = new javax.swing.JTextField();
        elderlyFirstTextField = new javax.swing.JTextField();
        elderlyMiddleTextField = new javax.swing.JTextField();
        personalInfoText = new javax.swing.JLabel();
        elderlyGuardianText = new javax.swing.JLabel();
        elderlyFirstText = new javax.swing.JLabel();
        elderlyMiddleText = new javax.swing.JLabel();
        elderlyAdmitDate = new com.toedter.calendar.JDateChooser();
        elderlySuffix = new javax.swing.JTextField();
        elderlyLastName = new javax.swing.JLabel();
        elderlyContact = new javax.swing.JTextField();
        elderlyProvinceText = new javax.swing.JLabel();
        elderlyGuardian = new javax.swing.JTextField();
        elderlyContactNoText = new javax.swing.JLabel();
        elderlySuffixText = new javax.swing.JLabel();
        elderlyStreet = new javax.swing.JTextField();
        elderlyAttendantIDText = new javax.swing.JLabel();
        elderlyBrgy = new javax.swing.JTextField();
        elderlyStreetText = new javax.swing.JLabel();
        elderlyCity = new javax.swing.JTextField();
        elderlyBrgyText = new javax.swing.JLabel();
        elderlyProvince = new javax.swing.JTextField();
        elderlyCityText = new javax.swing.JLabel();
        elderlyAddressText = new javax.swing.JLabel();
        elderlyBirthdate = new com.toedter.calendar.JDateChooser();
        elderlyAttendantID = new javax.swing.JTextField();
        elderlyAdmitDateText = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        updateElderlyButton = new javax.swing.JButton();
        elderlyGender = new javax.swing.JTextField();
        elderlyGenderText = new javax.swing.JLabel();
        elderlyIDText = new javax.swing.JLabel();
        elderlyRoomNoText = new javax.swing.JLabel();
        elderlyID = new javax.swing.JTextField();
        elderlyRoomNo = new javax.swing.JTextField();
        elderlyBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("St. Jude Care Facility");
        setIconImage(logo.getImage());
        setName("dashboardFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minimizeLogo.png"))); // NOI18N
        minimizeLogo.setToolTipText("Minimize");
        minimizeLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeLogo.setFocusable(false);
        minimizeLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLogoMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        elderlyInformationText.setFont(new java.awt.Font("Verdana Pro Black", 1, 28)); // NOI18N
        elderlyInformationText.setForeground(new java.awt.Color(129, 159, 29));
        elderlyInformationText.setText("ELDERLY INFORMATION");
        elderlyInformationText.setFocusable(false);
        getContentPane().add(elderlyInformationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 420, 30));

        personalInfoBG.setBackground(new java.awt.Color(255, 255, 255));
        personalInfoBG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 159, 29), 5, true));
        personalInfoBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        elderlyBirthdateText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyBirthdateText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyBirthdateText.setText("Birthdate*");
        elderlyBirthdateText.setFocusable(false);
        personalInfoBG.add(elderlyBirthdateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        elderlyLastTextField.setBackground(new java.awt.Color(231, 228, 228));
        elderlyLastTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyLastTextField.setForeground(new java.awt.Color(107, 132, 22));
        elderlyLastTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyLastTextField.setToolTipText("Last Name");
        elderlyLastTextField.setBorder(null);
        elderlyLastTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyLastTextFieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyLastTextFieldMousePressed(evt);
            }
        });
        elderlyLastTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyLastTextFieldActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyLastTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, 40));

        elderlyFirstTextField.setBackground(new java.awt.Color(231, 228, 228));
        elderlyFirstTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyFirstTextField.setForeground(new java.awt.Color(107, 132, 22));
        elderlyFirstTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyFirstTextField.setToolTipText("First Name");
        elderlyFirstTextField.setBorder(null);
        elderlyFirstTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyFirstTextFieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyFirstTextFieldMousePressed(evt);
            }
        });
        elderlyFirstTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyFirstTextFieldActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyFirstTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 150, 40));

        elderlyMiddleTextField.setBackground(new java.awt.Color(231, 228, 228));
        elderlyMiddleTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyMiddleTextField.setForeground(new java.awt.Color(107, 132, 22));
        elderlyMiddleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyMiddleTextField.setToolTipText("Middle Name");
        elderlyMiddleTextField.setBorder(null);
        elderlyMiddleTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyMiddleTextFieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyMiddleTextFieldMousePressed(evt);
            }
        });
        elderlyMiddleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyMiddleTextFieldActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyMiddleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 150, 40));

        personalInfoText.setFont(new java.awt.Font("Verdana Pro Black", 1, 18)); // NOI18N
        personalInfoText.setForeground(new java.awt.Color(183, 216, 72));
        personalInfoText.setText("PERSONAL INFORMATION");
        personalInfoText.setFocusable(false);
        personalInfoBG.add(personalInfoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 20));

        elderlyGuardianText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyGuardianText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyGuardianText.setText("Guardian Name*");
        elderlyGuardianText.setFocusable(false);
        personalInfoBG.add(elderlyGuardianText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 110, 20));

        elderlyFirstText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyFirstText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyFirstText.setText("First Name*");
        elderlyFirstText.setFocusable(false);
        personalInfoBG.add(elderlyFirstText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 80, 20));

        elderlyMiddleText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyMiddleText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyMiddleText.setText("Middle Name");
        elderlyMiddleText.setFocusable(false);
        personalInfoBG.add(elderlyMiddleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 80, 20));

        elderlyAdmitDate.setBackground(new java.awt.Color(231, 228, 228));
        elderlyAdmitDate.setForeground(new java.awt.Color(107, 132, 22));
        elderlyAdmitDate.setToolTipText("Admit Date");
        elderlyAdmitDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        personalInfoBG.add(elderlyAdmitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 290, 40));

        elderlySuffix.setBackground(new java.awt.Color(231, 228, 228));
        elderlySuffix.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlySuffix.setForeground(new java.awt.Color(107, 132, 22));
        elderlySuffix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlySuffix.setToolTipText("Suffix Name");
        elderlySuffix.setBorder(null);
        elderlySuffix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlySuffixMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlySuffixMousePressed(evt);
            }
        });
        elderlySuffix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlySuffixActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlySuffix, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 80, 40));

        elderlyLastName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyLastName.setForeground(new java.awt.Color(107, 132, 22));
        elderlyLastName.setText("Last Name*");
        elderlyLastName.setFocusable(false);
        personalInfoBG.add(elderlyLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, 20));

        elderlyContact.setBackground(new java.awt.Color(231, 228, 228));
        elderlyContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyContact.setForeground(new java.awt.Color(107, 132, 22));
        elderlyContact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyContact.setToolTipText("Contact Number");
        elderlyContact.setBorder(null);
        elderlyContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyContactMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyContactMousePressed(evt);
            }
        });
        elderlyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyContactActionPerformed(evt);
            }
        });
        elderlyContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                elderlyContactKeyTyped(evt);
            }
        });
        personalInfoBG.add(elderlyContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 240, 40));

        elderlyProvinceText.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        elderlyProvinceText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyProvinceText.setText("Province*");
        elderlyProvinceText.setFocusable(false);
        personalInfoBG.add(elderlyProvinceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 110, 20));

        elderlyGuardian.setBackground(new java.awt.Color(231, 228, 228));
        elderlyGuardian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyGuardian.setForeground(new java.awt.Color(107, 132, 22));
        elderlyGuardian.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyGuardian.setToolTipText("Guardian Name");
        elderlyGuardian.setBorder(null);
        elderlyGuardian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyGuardianMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyGuardianMousePressed(evt);
            }
        });
        elderlyGuardian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyGuardianActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyGuardian, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 280, 40));

        elderlyContactNoText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyContactNoText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyContactNoText.setText("Contact Number*");
        elderlyContactNoText.setFocusable(false);
        personalInfoBG.add(elderlyContactNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 110, 20));

        elderlySuffixText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlySuffixText.setForeground(new java.awt.Color(107, 132, 22));
        elderlySuffixText.setText("Suffix Name");
        elderlySuffixText.setFocusable(false);
        personalInfoBG.add(elderlySuffixText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 80, 20));

        elderlyStreet.setBackground(new java.awt.Color(231, 228, 228));
        elderlyStreet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyStreet.setForeground(new java.awt.Color(107, 132, 22));
        elderlyStreet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyStreet.setToolTipText("Street");
        elderlyStreet.setBorder(null);
        elderlyStreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyStreetMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyStreetMousePressed(evt);
            }
        });
        elderlyStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyStreetActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 30));

        elderlyAttendantIDText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyAttendantIDText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyAttendantIDText.setText("Assign to AttendantID*");
        elderlyAttendantIDText.setFocusable(false);
        personalInfoBG.add(elderlyAttendantIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 150, 20));

        elderlyBrgy.setBackground(new java.awt.Color(231, 228, 228));
        elderlyBrgy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyBrgy.setForeground(new java.awt.Color(107, 132, 22));
        elderlyBrgy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyBrgy.setToolTipText("Barangay");
        elderlyBrgy.setBorder(null);
        elderlyBrgy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyBrgyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyBrgyMousePressed(evt);
            }
        });
        elderlyBrgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyBrgyActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyBrgy, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, 30));

        elderlyStreetText.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        elderlyStreetText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyStreetText.setText("Street*");
        elderlyStreetText.setFocusable(false);
        personalInfoBG.add(elderlyStreetText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 20));

        elderlyCity.setBackground(new java.awt.Color(231, 228, 228));
        elderlyCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyCity.setForeground(new java.awt.Color(107, 132, 22));
        elderlyCity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyCity.setToolTipText("City");
        elderlyCity.setBorder(null);
        elderlyCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyCityMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyCityMousePressed(evt);
            }
        });
        elderlyCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyCityActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 210, 30));

        elderlyBrgyText.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        elderlyBrgyText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyBrgyText.setText("Barangay*");
        elderlyBrgyText.setFocusable(false);
        personalInfoBG.add(elderlyBrgyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 110, 20));

        elderlyProvince.setBackground(new java.awt.Color(231, 228, 228));
        elderlyProvince.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyProvince.setForeground(new java.awt.Color(107, 132, 22));
        elderlyProvince.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyProvince.setToolTipText("Province");
        elderlyProvince.setBorder(null);
        elderlyProvince.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyProvinceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyProvinceMousePressed(evt);
            }
        });
        elderlyProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyProvinceActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 130, 30));

        elderlyCityText.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        elderlyCityText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyCityText.setText("City/Municipality*");
        elderlyCityText.setFocusable(false);
        personalInfoBG.add(elderlyCityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 110, 20));

        elderlyAddressText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyAddressText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyAddressText.setText("Elderly's Address");
        elderlyAddressText.setFocusable(false);
        personalInfoBG.add(elderlyAddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 20));

        elderlyBirthdate.setBackground(new java.awt.Color(231, 228, 228));
        elderlyBirthdate.setForeground(new java.awt.Color(107, 132, 22));
        elderlyBirthdate.setToolTipText("Birth Date");
        elderlyBirthdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyBirthdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyBirthdateMousePressed(evt);
            }
        });
        personalInfoBG.add(elderlyBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 40));

        elderlyAttendantID.setBackground(new java.awt.Color(231, 228, 228));
        elderlyAttendantID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyAttendantID.setForeground(new java.awt.Color(107, 132, 22));
        elderlyAttendantID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyAttendantID.setToolTipText("Attendant ID");
        elderlyAttendantID.setBorder(null);
        elderlyAttendantID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyAttendantIDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyAttendantIDMousePressed(evt);
            }
        });
        elderlyAttendantID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyAttendantIDActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyAttendantID, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 200, 40));

        elderlyAdmitDateText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyAdmitDateText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyAdmitDateText.setText("Admit Date*");
        elderlyAdmitDateText.setFocusable(false);
        personalInfoBG.add(elderlyAdmitDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, 20));

        backButton.setBackground(new java.awt.Color(176, 212, 55));
        backButton.setFont(new java.awt.Font("Verdana Pro Black", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("GO BACK");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        personalInfoBG.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 210, 40));

        updateElderlyButton.setBackground(new java.awt.Color(176, 212, 55));
        updateElderlyButton.setFont(new java.awt.Font("Verdana Pro Black", 1, 18)); // NOI18N
        updateElderlyButton.setForeground(new java.awt.Color(255, 255, 255));
        updateElderlyButton.setText("UPDATE ELDERLY");
        updateElderlyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateElderlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateElderlyButtonActionPerformed(evt);
            }
        });
        personalInfoBG.add(updateElderlyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 250, 40));

        elderlyGender.setBackground(new java.awt.Color(231, 228, 228));
        elderlyGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyGender.setForeground(new java.awt.Color(107, 132, 22));
        elderlyGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyGender.setToolTipText("Gender");
        elderlyGender.setBorder(null);
        elderlyGender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elderlyGenderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyGenderMousePressed(evt);
            }
        });
        elderlyGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderlyGenderActionPerformed(evt);
            }
        });
        personalInfoBG.add(elderlyGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 110, 40));

        elderlyGenderText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyGenderText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyGenderText.setText("Gender*");
        elderlyGenderText.setFocusable(false);
        personalInfoBG.add(elderlyGenderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 80, 20));

        elderlyIDText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyIDText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyIDText.setText("ElderlyID*");
        elderlyIDText.setFocusable(false);
        personalInfoBG.add(elderlyIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 20));

        elderlyRoomNoText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyRoomNoText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyRoomNoText.setText("Room Number*");
        elderlyRoomNoText.setFocusable(false);
        personalInfoBG.add(elderlyRoomNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 110, 20));

        elderlyID.setBackground(new java.awt.Color(231, 228, 228));
        elderlyID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyID.setForeground(new java.awt.Color(107, 132, 22));
        elderlyID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyID.setToolTipText("Elderly ID");
        elderlyID.setBorder(null);
        elderlyID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyIDMousePressed(evt);
            }
        });
        elderlyID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                elderlyIDKeyTyped(evt);
            }
        });
        personalInfoBG.add(elderlyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 40));

        elderlyRoomNo.setBackground(new java.awt.Color(231, 228, 228));
        elderlyRoomNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elderlyRoomNo.setForeground(new java.awt.Color(107, 132, 22));
        elderlyRoomNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elderlyRoomNo.setToolTipText("Room Number");
        elderlyRoomNo.setBorder(null);
        elderlyRoomNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elderlyRoomNoMousePressed(evt);
            }
        });
        elderlyRoomNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                elderlyRoomNoKeyTyped(evt);
            }
        });
        personalInfoBG.add(elderlyRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 270, 40));

        getContentPane().add(personalInfoBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 840, 390));

        elderlyBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboardBackground.png"))); // NOI18N
        elderlyBackground.setText("jLabel1");
        elderlyBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 159, 29), 10, true));
        elderlyBackground.setPreferredSize(new java.awt.Dimension(1020, 570));
        getContentPane().add(elderlyBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void elderlyLastTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyLastTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyLastTextFieldMouseClicked

    private void elderlyLastTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyLastTextFieldMousePressed
        if(elderlyLastTextField.getText().equals("Last Name")){
            elderlyLastTextField.setText("");
            elderlyLastTextField.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyLastTextFieldMousePressed

    private void elderlyLastTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyLastTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyLastTextFieldActionPerformed

    private void elderlyFirstTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyFirstTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyFirstTextFieldMouseClicked

    private void elderlyFirstTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyFirstTextFieldMousePressed
        if(elderlyFirstTextField.getText().equals("First Name")){
            elderlyFirstTextField.setText("");
            elderlyFirstTextField.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyFirstTextFieldMousePressed

    private void elderlyFirstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyFirstTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyFirstTextFieldActionPerformed

    private void elderlyMiddleTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyMiddleTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyMiddleTextFieldMouseClicked

    private void elderlyMiddleTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyMiddleTextFieldMousePressed
        if(elderlyMiddleTextField.getText().equals("Middle Name")){
            elderlyMiddleTextField.setText("");
            elderlyMiddleTextField.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyMiddleTextFieldMousePressed

    private void elderlyMiddleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyMiddleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyMiddleTextFieldActionPerformed

    private void elderlySuffixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlySuffixMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlySuffixMouseClicked

    private void elderlySuffixMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlySuffixMousePressed
        if(elderlySuffix.getText().equals("Suffix name")){
            elderlySuffix.setText("");
            elderlySuffix.setFocusable(true);
        }
    }//GEN-LAST:event_elderlySuffixMousePressed

    private void elderlySuffixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlySuffixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlySuffixActionPerformed

    private void elderlyContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyContactMouseClicked

    }//GEN-LAST:event_elderlyContactMouseClicked

    private void elderlyContactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyContactMousePressed
        if(elderlyContact.getText().equals("Contact Number")){
            elderlyContact.setText("");
            elderlyContact.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyContactMousePressed

    private void elderlyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyContactActionPerformed

    private void elderlyGuardianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyGuardianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyGuardianMouseClicked

    private void elderlyGuardianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyGuardianMousePressed
        if(elderlyGuardian.getText().equals("Guardian Name")){
            elderlyGuardian.setText("");
            elderlyGuardian.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyGuardianMousePressed

    private void elderlyGuardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyGuardianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyGuardianActionPerformed

    private void elderlyStreetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyStreetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyStreetMouseClicked

    private void elderlyStreetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyStreetMousePressed
        if(elderlyStreet.getText().equals("Street")){
            elderlyStreet.setText("");
            elderlyStreet.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyStreetMousePressed

    private void elderlyStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyStreetActionPerformed

    private void elderlyBrgyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyBrgyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyBrgyMouseClicked

    private void elderlyBrgyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyBrgyMousePressed
        if(elderlyBrgy.getText().equals("Barangay")){
            elderlyBrgy.setText("");
            elderlyBrgy.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyBrgyMousePressed

    private void elderlyBrgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyBrgyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyBrgyActionPerformed

    private void elderlyCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyCityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyCityMouseClicked

    private void elderlyCityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyCityMousePressed
        if(elderlyCity.getText().equals("City")){
            elderlyCity.setText("");
            elderlyCity.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyCityMousePressed

    private void elderlyCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyCityActionPerformed

    private void elderlyProvinceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyProvinceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyProvinceMouseClicked

    private void elderlyProvinceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyProvinceMousePressed
        if(elderlyProvince.getText().equals("Province")){
            elderlyProvince.setText("");
            elderlyProvince.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyProvinceMousePressed

    private void elderlyProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyProvinceActionPerformed

    private void elderlyAttendantIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyAttendantIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyAttendantIDMouseClicked

    private void elderlyAttendantIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyAttendantIDMousePressed
        if(elderlyAttendantID.getText().equals("Assign to AttendantID")){
            elderlyAttendantID.setText("");
            elderlyAttendantID.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyAttendantIDMousePressed

    private void elderlyAttendantIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyAttendantIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyAttendantIDActionPerformed

    private void updateElderlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateElderlyButtonActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DatabaseConnection.DB_CONNECTION,"root","root");
            String sql = "UPDATE elderly SET LastName = ?, FirstName = ?, MiddleName = ?, SuffixName = ?, Gender = ?, BirthDate = ?, ContactNo = ?, GuardianName = ?, Street = ?, Barangay = ?, CityMunicipality = ?, Province = ?, AdmitDate = ?, ElderlyRoomNo = ?, AttendantID = ? WHERE ElderlyID = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            String lastName = elderlyLastTextField.getText();
            pst.setString(1, lastName);
            String firstName = elderlyFirstTextField.getText();
            pst.setString(2, firstName);
            String middleName = elderlyMiddleTextField.getText();
            pst.setString(3, middleName);
            String suffixName = elderlySuffix.getText();
            pst.setString(4, suffixName);
            String gender = elderlyGender.getText();
            pst.setString(5, gender);
            String guardian = elderlyGuardian.getText();
            pst.setString(8, guardian);
            String street = elderlyStreet.getText();
            pst.setString(9, street);
            String brgy = elderlyBrgy.getText();
            pst.setString(10, brgy);
            String city = elderlyCity.getText();
            pst.setString(11, city);
            String province = elderlyProvince.getText();
            pst.setString(12, province);
            int elderlyroomno = Integer.parseInt(elderlyRoomNo.getText());
            pst.setInt(14, elderlyroomno);
            int elderlyattendantid = Integer.parseInt(elderlyAttendantID.getText());
            pst.setInt(15, elderlyattendantid);
            int elderlyid = Integer.parseInt(elderlyID.getText());
            pst.setInt(16, elderlyid);

            //Date
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDate birthDate = elderlyBirthdate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String formattedBirthDate = birthDate.format(formatter);
            pst.setString(6, formattedBirthDate);
            
            LocalDate admitDate = elderlyAdmitDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String formattedAdmitDate = admitDate.format(formatter);
            pst.setString(13, formattedAdmitDate);

            //Contact Number
            String contactNo = elderlyContact.getText();
            
            if(contactNo.length() == 11){
                long ContactNo = Long.parseLong(contactNo);
                pst.setString(7, Long.toString(ContactNo));

            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Contact Number");
            }
            
            pst.executeUpdate();
            
            ElderlyDetails elderlyDetails = new ElderlyDetails();
            elderlyDetails.setVisible(true);
            this.setVisible(false);
            pst.close();
            con.close();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Connection Error!" + e.getMessage());
        }
        
        ElderlyDetails elderlyDetails = new ElderlyDetails();
         String database = "SELECT ElderlyID, FirstName, MiddleName, LastName, SuffixName, Gender, BirthDate, ContactNo, GuardianName, Street, Barangay, CityMunicipality, Province, AdmitDate, ElderlyRoomNo FROM elderly";
         
         try{
             Connection con = DriverManager.getConnection(DatabaseConnection.DB_CONNECTION,"root","root");
             PreparedStatement pst = con.prepareStatement(database);
             ResultSet rs = pst.executeQuery();
             DefaultTableModel table = (DefaultTableModel) elderlyDetails.getElderlyTable().getModel();
             table.setRowCount(0);
             
             while(rs.next()){
                 Object[] row = {
                     rs.getInt("ElderlyID"),
                     rs.getString("FirstName"),
                     rs.getString("MiddleName"),
                     rs.getString("LastName"),
                     rs.getString("SuffixName"),
                     rs.getString("Gender"),
                     rs.getObject("BirthDate"),
                     rs.getLong("ContactNo"),
                     rs.getString("GuardianName"),
                     rs.getString("Street"),
                     rs.getString("Barangay"),
                     rs.getString("CityMunicipality"),
                     rs.getString("Province"),
                     rs.getObject("AdmitDate"),
                     rs.getLong("ElderlyRoomNo")
                 };
                 table.addRow(row);
             }
             elderlyDetails.getElderlyTable().setModel(table);
             elderlyDetails.setVisible(true);
             this.setVisible(false);
             rs.close();
             pst.close();
             con.close();
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Connection Error!" + e.getMessage());
         }
    }//GEN-LAST:event_updateElderlyButtonActionPerformed

    private void elderlyGenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyGenderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyGenderMouseClicked

    private void elderlyGenderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyGenderMousePressed
        if(elderlyGender.getText().equals("Gender")){
            elderlyGender.setText("");
            elderlyGender.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyGenderMousePressed

    private void elderlyGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderlyGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elderlyGenderActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        elderlyLastTextField.setFocusable(true);
        elderlyFirstTextField.setFocusable(true);
        elderlyMiddleTextField.setFocusable(true);
        elderlySuffix.setFocusable(true);
        elderlyGender.setFocusable(true);
        elderlyBirthdate.setFocusable(true);
        elderlyContact.setFocusable(true);
        elderlyGuardian.setFocusable(true);
        elderlyStreet.setFocusable(true);
        elderlyBrgy.setFocusable(true);
        elderlyCity.setFocusable(true);
        elderlyProvince.setFocusable(true);
        elderlyAdmitDate.setFocusable(true);
        elderlyRoomNo.setFocusable(true);
        elderlyAttendantID.setFocusable(true);
    }//GEN-LAST:event_formMouseEntered

    private void elderlyBirthdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyBirthdateMousePressed

    }//GEN-LAST:event_elderlyBirthdateMousePressed

    private void elderlyRoomNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyRoomNoMousePressed
        if(elderlyRoomNo.getText().equals("Room Number")){
            elderlyRoomNo.setText("");
            elderlyRoomNo.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyRoomNoMousePressed

    private void elderlyContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elderlyContactKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_elderlyContactKeyTyped

    private void elderlyRoomNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elderlyRoomNoKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_elderlyRoomNoKeyTyped

    private void minimizeLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLogoMouseClicked
        this.setExtendedState(ElderlyUpdate.ICONIFIED);
    }//GEN-LAST:event_minimizeLogoMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         ElderlyDetails elderlyDetails = new ElderlyDetails();
         String database = "SELECT ElderlyID, FirstName, MiddleName, LastName, SuffixName, Gender, BirthDate, ContactNo, GuardianName, Street, Barangay, CityMunicipality, Province, AdmitDate, ElderlyRoomNo FROM elderly";
         
         try{
             Connection con = DriverManager.getConnection(DatabaseConnection.DB_CONNECTION,"root","root");
             PreparedStatement pst = con.prepareStatement(database);
             ResultSet rs = pst.executeQuery();
             DefaultTableModel table = (DefaultTableModel) elderlyDetails.getElderlyTable().getModel();
             table.setRowCount(0);
             
             while(rs.next()){
                 Object[] row = {
                     rs.getInt("ElderlyID"),
                     rs.getString("FirstName"),
                     rs.getString("MiddleName"),
                     rs.getString("LastName"),
                     rs.getString("SuffixName"),
                     rs.getString("Gender"),
                     rs.getObject("BirthDate"),
                     rs.getLong("ContactNo"),
                     rs.getString("GuardianName"),
                     rs.getString("Street"),
                     rs.getString("Barangay"),
                     rs.getString("CityMunicipality"),
                     rs.getString("Province"),
                     rs.getObject("AdmitDate"),
                     rs.getLong("ElderlyRoomNo")
                 };
                 table.addRow(row);
             }
             elderlyDetails.getElderlyTable().setModel(table);
             elderlyDetails.setVisible(true);
             this.setVisible(false);
             rs.close();
             pst.close();
             con.close();
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Connection Error!" + e.getMessage());
         }
    }//GEN-LAST:event_backButtonActionPerformed

    private void elderlyIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elderlyIDMousePressed
        if(elderlyID.getText().equals("Elderly ID")){
            elderlyID.setText("");
            elderlyID.setFocusable(true);
        }
    }//GEN-LAST:event_elderlyIDMousePressed

    private void elderlyIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elderlyIDKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_elderlyIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElderlyUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElderlyUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElderlyUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElderlyUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElderlyUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel elderlyAddressText;
    private com.toedter.calendar.JDateChooser elderlyAdmitDate;
    private javax.swing.JLabel elderlyAdmitDateText;
    private javax.swing.JTextField elderlyAttendantID;
    private javax.swing.JLabel elderlyAttendantIDText;
    private javax.swing.JLabel elderlyBackground;
    private com.toedter.calendar.JDateChooser elderlyBirthdate;
    private javax.swing.JLabel elderlyBirthdateText;
    private javax.swing.JTextField elderlyBrgy;
    private javax.swing.JLabel elderlyBrgyText;
    private javax.swing.JTextField elderlyCity;
    private javax.swing.JLabel elderlyCityText;
    private javax.swing.JTextField elderlyContact;
    private javax.swing.JLabel elderlyContactNoText;
    private javax.swing.JLabel elderlyFirstText;
    private javax.swing.JTextField elderlyFirstTextField;
    private javax.swing.JTextField elderlyGender;
    private javax.swing.JLabel elderlyGenderText;
    private javax.swing.JTextField elderlyGuardian;
    private javax.swing.JLabel elderlyGuardianText;
    private javax.swing.JTextField elderlyID;
    private javax.swing.JLabel elderlyIDText;
    private javax.swing.JLabel elderlyInformationText;
    private javax.swing.JLabel elderlyLastName;
    private javax.swing.JTextField elderlyLastTextField;
    private javax.swing.JLabel elderlyMiddleText;
    private javax.swing.JTextField elderlyMiddleTextField;
    private javax.swing.JTextField elderlyProvince;
    private javax.swing.JLabel elderlyProvinceText;
    private javax.swing.JTextField elderlyRoomNo;
    private javax.swing.JLabel elderlyRoomNoText;
    private javax.swing.JTextField elderlyStreet;
    private javax.swing.JLabel elderlyStreetText;
    private javax.swing.JTextField elderlySuffix;
    private javax.swing.JLabel elderlySuffixText;
    private javax.swing.JLabel minimizeLogo;
    private javax.swing.JPanel personalInfoBG;
    private javax.swing.JLabel personalInfoText;
    private javax.swing.JButton updateElderlyButton;
    // End of variables declaration//GEN-END:variables
}
