/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visitormanagementsystem;

import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author justi
 */
public class VisitorUpdate extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    ImageIcon logo = new ImageIcon("C:\\Users\\justi\\Desktop\\Programming\\Java\\VisitorManagementSystem\\src\\assets\\SJCF_LOGO.png");
    
    public VisitorUpdate() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        visitorLastTextField.setFocusable(false);
        visitorFirstTextField.setFocusable(false);
        visitorMiddleTextField.setFocusable(false);
        visitorSuffix.setFocusable(false);
        visitorGender.setFocusable(false);
        visitorContact.setFocusable(false);
        visitorEmail.setFocusable(false);
        visitorRelationship.setFocusable(false);
        visitorBrgy.setFocusable(false);
        visitorCity.setFocusable(false);
        visitorProvince.setFocusable(false);
        visitorRelationship.setFocusable(false);
        visitorVisitTime.setFocusable(false);
        visitVisitorID.setFocusable(false);
        visitElderlyID.setFocusable(false);
        visitorID.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visitorInformationText = new javax.swing.JLabel();
        minimizeLogo = new javax.swing.JLabel();
        personalInfoBG = new javax.swing.JPanel();
        visitorLastTextField = new javax.swing.JTextField();
        visitorFirstTextField = new javax.swing.JTextField();
        visitorMiddleTextField = new javax.swing.JTextField();
        personalInfoText = new javax.swing.JLabel();
        visitorFirstText = new javax.swing.JLabel();
        visitorMiddleText = new javax.swing.JLabel();
        visitorLastName = new javax.swing.JLabel();
        visitorProvinceText = new javax.swing.JLabel();
        visitorBrgy = new javax.swing.JTextField();
        visitorStreetText = new javax.swing.JLabel();
        visitorCity = new javax.swing.JTextField();
        visitorBrgyText = new javax.swing.JLabel();
        visitorProvince = new javax.swing.JTextField();
        visitorCityText = new javax.swing.JLabel();
        visitorAddressText = new javax.swing.JLabel();
        visitorSuffix = new javax.swing.JTextField();
        visitorSuffixText = new javax.swing.JLabel();
        visitorGenderText = new javax.swing.JLabel();
        visitorGender = new javax.swing.JTextField();
        visitorBirthdateText = new javax.swing.JLabel();
        visitorBirthdate = new com.toedter.calendar.JDateChooser();
        visitorContactNoText = new javax.swing.JLabel();
        visitorContact = new javax.swing.JTextField();
        visitorEmailText = new javax.swing.JLabel();
        visitorEmail = new javax.swing.JTextField();
        visitorStreet = new javax.swing.JTextField();
        updateVisitorButton = new javax.swing.JButton();
        visitorRelationshipText = new javax.swing.JLabel();
        visitorRelationship = new javax.swing.JTextField();
        visitorID = new javax.swing.JTextField();
        visitorIDText = new javax.swing.JLabel();
        personalVisitInfoBG = new javax.swing.JPanel();
        visitorVisitDate = new com.toedter.calendar.JDateChooser();
        visitElderlyID = new javax.swing.JTextField();
        visitVisitorID = new javax.swing.JTextField();
        visitorVisitTime = new javax.swing.JTextField();
        updateDateButton = new javax.swing.JButton();
        visitorAdmitTimeText = new javax.swing.JLabel();
        elderlyIDText = new javax.swing.JLabel();
        visitVisitorIDText = new javax.swing.JLabel();
        visitorAdmitDateText = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        dateInfoText = new javax.swing.JLabel();
        visitorBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("St. Jude Care Facility");
        setName("dashboardFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visitorInformationText.setFont(new java.awt.Font("Verdana Pro Black", 1, 28)); // NOI18N
        visitorInformationText.setForeground(new java.awt.Color(129, 159, 29));
        visitorInformationText.setText("VISITOR INFORMATION");
        visitorInformationText.setFocusable(false);
        getContentPane().add(visitorInformationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 420, 30));

        minimizeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minimizeLogo.png"))); // NOI18N
        minimizeLogo.setToolTipText("Minimize");
        minimizeLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeLogo.setFocusable(false);
        minimizeLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLogoMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        personalInfoBG.setBackground(new java.awt.Color(255, 255, 255));
        personalInfoBG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 159, 29), 5, true));
        personalInfoBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visitorLastTextField.setBackground(new java.awt.Color(231, 228, 228));
        visitorLastTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorLastTextField.setForeground(new java.awt.Color(107, 132, 22));
        visitorLastTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorLastTextField.setToolTipText("Last Name");
        visitorLastTextField.setBorder(null);
        visitorLastTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorLastTextFieldMousePressed(evt);
            }
        });
        visitorLastTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorLastTextFieldActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorLastTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, 40));

        visitorFirstTextField.setBackground(new java.awt.Color(231, 228, 228));
        visitorFirstTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorFirstTextField.setForeground(new java.awt.Color(107, 132, 22));
        visitorFirstTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorFirstTextField.setBorder(null);
        visitorFirstTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorFirstTextFieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorFirstTextFieldMousePressed(evt);
            }
        });
        visitorFirstTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorFirstTextFieldActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorFirstTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 150, 40));

        visitorMiddleTextField.setBackground(new java.awt.Color(231, 228, 228));
        visitorMiddleTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorMiddleTextField.setForeground(new java.awt.Color(107, 132, 22));
        visitorMiddleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorMiddleTextField.setBorder(null);
        visitorMiddleTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorMiddleTextFieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorMiddleTextFieldMousePressed(evt);
            }
        });
        visitorMiddleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorMiddleTextFieldActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorMiddleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 150, 40));

        personalInfoText.setFont(new java.awt.Font("Verdana Pro Black", 1, 18)); // NOI18N
        personalInfoText.setForeground(new java.awt.Color(183, 216, 72));
        personalInfoText.setText("PERSONAL INFORMATION");
        personalInfoText.setFocusable(false);
        personalInfoBG.add(personalInfoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 20));

        visitorFirstText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorFirstText.setForeground(new java.awt.Color(107, 132, 22));
        visitorFirstText.setText("First Name*");
        visitorFirstText.setFocusable(false);
        personalInfoBG.add(visitorFirstText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 80, 20));

        visitorMiddleText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorMiddleText.setForeground(new java.awt.Color(107, 132, 22));
        visitorMiddleText.setText("Middle Name");
        visitorMiddleText.setFocusable(false);
        personalInfoBG.add(visitorMiddleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 80, 20));

        visitorLastName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorLastName.setForeground(new java.awt.Color(107, 132, 22));
        visitorLastName.setText("Last Name*");
        visitorLastName.setFocusable(false);
        personalInfoBG.add(visitorLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 80, 20));

        visitorProvinceText.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        visitorProvinceText.setForeground(new java.awt.Color(107, 132, 22));
        visitorProvinceText.setText("Province*");
        visitorProvinceText.setFocusable(false);
        personalInfoBG.add(visitorProvinceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 110, 20));

        visitorBrgy.setBackground(new java.awt.Color(231, 228, 228));
        visitorBrgy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorBrgy.setForeground(new java.awt.Color(107, 132, 22));
        visitorBrgy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorBrgy.setBorder(null);
        visitorBrgy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorBrgyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorBrgyMousePressed(evt);
            }
        });
        visitorBrgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorBrgyActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorBrgy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 230, 30));

        visitorStreetText.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        visitorStreetText.setForeground(new java.awt.Color(107, 132, 22));
        visitorStreetText.setText("Street*");
        visitorStreetText.setFocusable(false);
        personalInfoBG.add(visitorStreetText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, 20));

        visitorCity.setBackground(new java.awt.Color(231, 228, 228));
        visitorCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorCity.setForeground(new java.awt.Color(107, 132, 22));
        visitorCity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorCity.setBorder(null);
        visitorCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorCityMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorCityMousePressed(evt);
            }
        });
        visitorCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorCityActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 210, 30));

        visitorBrgyText.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        visitorBrgyText.setForeground(new java.awt.Color(107, 132, 22));
        visitorBrgyText.setText("Barangay*");
        visitorBrgyText.setFocusable(false);
        personalInfoBG.add(visitorBrgyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 110, 20));

        visitorProvince.setBackground(new java.awt.Color(231, 228, 228));
        visitorProvince.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorProvince.setForeground(new java.awt.Color(107, 132, 22));
        visitorProvince.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorProvince.setBorder(null);
        visitorProvince.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorProvinceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorProvinceMousePressed(evt);
            }
        });
        visitorProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorProvinceActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 130, 30));

        visitorCityText.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        visitorCityText.setForeground(new java.awt.Color(107, 132, 22));
        visitorCityText.setText("City/Municipality*");
        visitorCityText.setFocusable(false);
        personalInfoBG.add(visitorCityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 110, 20));

        visitorAddressText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorAddressText.setForeground(new java.awt.Color(107, 132, 22));
        visitorAddressText.setText("Visitor's Address");
        visitorAddressText.setFocusable(false);
        personalInfoBG.add(visitorAddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 20));

        visitorSuffix.setBackground(new java.awt.Color(231, 228, 228));
        visitorSuffix.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorSuffix.setForeground(new java.awt.Color(107, 132, 22));
        visitorSuffix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorSuffix.setBorder(null);
        visitorSuffix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorSuffixMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorSuffixMousePressed(evt);
            }
        });
        visitorSuffix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorSuffixActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorSuffix, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 80, 40));

        visitorSuffixText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorSuffixText.setForeground(new java.awt.Color(107, 132, 22));
        visitorSuffixText.setText("Suffix Name");
        visitorSuffixText.setFocusable(false);
        personalInfoBG.add(visitorSuffixText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 80, 20));

        visitorGenderText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorGenderText.setForeground(new java.awt.Color(107, 132, 22));
        visitorGenderText.setText("Gender*");
        visitorGenderText.setFocusable(false);
        personalInfoBG.add(visitorGenderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 80, 20));

        visitorGender.setBackground(new java.awt.Color(231, 228, 228));
        visitorGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorGender.setForeground(new java.awt.Color(107, 132, 22));
        visitorGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorGender.setBorder(null);
        visitorGender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorGenderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorGenderMousePressed(evt);
            }
        });
        visitorGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorGenderActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 110, 40));

        visitorBirthdateText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorBirthdateText.setForeground(new java.awt.Color(107, 132, 22));
        visitorBirthdateText.setText("Birthdate*");
        visitorBirthdateText.setFocusable(false);
        personalInfoBG.add(visitorBirthdateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 20));

        visitorBirthdate.setBackground(new java.awt.Color(231, 228, 228));
        visitorBirthdate.setForeground(new java.awt.Color(107, 132, 22));
        visitorBirthdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        personalInfoBG.add(visitorBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 40));

        visitorContactNoText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorContactNoText.setForeground(new java.awt.Color(107, 132, 22));
        visitorContactNoText.setText("Contact Number*");
        visitorContactNoText.setFocusable(false);
        personalInfoBG.add(visitorContactNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 110, 20));

        visitorContact.setBackground(new java.awt.Color(231, 228, 228));
        visitorContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorContact.setForeground(new java.awt.Color(107, 132, 22));
        visitorContact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorContact.setBorder(null);
        visitorContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorContactMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorContactMousePressed(evt);
            }
        });
        visitorContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorContactActionPerformed(evt);
            }
        });
        visitorContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                visitorContactKeyTyped(evt);
            }
        });
        personalInfoBG.add(visitorContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 240, 40));

        visitorEmailText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorEmailText.setForeground(new java.awt.Color(107, 132, 22));
        visitorEmailText.setText("Email Address*");
        visitorEmailText.setFocusable(false);
        personalInfoBG.add(visitorEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 110, 20));

        visitorEmail.setBackground(new java.awt.Color(231, 228, 228));
        visitorEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorEmail.setForeground(new java.awt.Color(107, 132, 22));
        visitorEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorEmail.setBorder(null);
        visitorEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorEmailMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorEmailMousePressed(evt);
            }
        });
        visitorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorEmailActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 280, 40));

        visitorStreet.setBackground(new java.awt.Color(231, 228, 228));
        visitorStreet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorStreet.setForeground(new java.awt.Color(107, 132, 22));
        visitorStreet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorStreet.setBorder(null);
        visitorStreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorStreetMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorStreetMousePressed(evt);
            }
        });
        visitorStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorStreetActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 30));

        updateVisitorButton.setBackground(new java.awt.Color(176, 212, 55));
        updateVisitorButton.setFont(new java.awt.Font("Verdana Pro Black", 1, 18)); // NOI18N
        updateVisitorButton.setForeground(new java.awt.Color(255, 255, 255));
        updateVisitorButton.setText("UPDATE VISITOR");
        updateVisitorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateVisitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVisitorButtonActionPerformed(evt);
            }
        });
        personalInfoBG.add(updateVisitorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 240, 40));

        visitorRelationshipText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorRelationshipText.setForeground(new java.awt.Color(107, 132, 22));
        visitorRelationshipText.setText("Relationship to Elderly*");
        visitorRelationshipText.setFocusable(false);
        personalInfoBG.add(visitorRelationshipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 140, 20));

        visitorRelationship.setBackground(new java.awt.Color(231, 228, 228));
        visitorRelationship.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorRelationship.setForeground(new java.awt.Color(107, 132, 22));
        visitorRelationship.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorRelationship.setBorder(null);
        visitorRelationship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorRelationshipMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorRelationshipMousePressed(evt);
            }
        });
        visitorRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorRelationshipActionPerformed(evt);
            }
        });
        personalInfoBG.add(visitorRelationship, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 390, 40));

        visitorID.setBackground(new java.awt.Color(231, 228, 228));
        visitorID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorID.setForeground(new java.awt.Color(107, 132, 22));
        visitorID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorID.setBorder(null);
        visitorID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorIDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorIDMousePressed(evt);
            }
        });
        visitorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorIDActionPerformed(evt);
            }
        });
        visitorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                visitorIDKeyTyped(evt);
            }
        });
        personalInfoBG.add(visitorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 40));

        visitorIDText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorIDText.setForeground(new java.awt.Color(107, 132, 22));
        visitorIDText.setText("VisitorID*");
        visitorIDText.setFocusable(false);
        personalInfoBG.add(visitorIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 20));

        getContentPane().add(personalInfoBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 840, 340));

        personalVisitInfoBG.setBackground(new java.awt.Color(255, 255, 255));
        personalVisitInfoBG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 159, 29), 5, true));
        personalVisitInfoBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visitorVisitDate.setBackground(new java.awt.Color(231, 228, 228));
        visitorVisitDate.setForeground(new java.awt.Color(107, 132, 22));
        visitorVisitDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorVisitDate.setName("visitorVisitDate"); // NOI18N
        visitorVisitDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorVisitDateMousePressed(evt);
            }
        });
        personalVisitInfoBG.add(visitorVisitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 210, 40));

        visitElderlyID.setBackground(new java.awt.Color(231, 228, 228));
        visitElderlyID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitElderlyID.setForeground(new java.awt.Color(107, 132, 22));
        visitElderlyID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitElderlyID.setBorder(null);
        visitElderlyID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitElderlyIDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitElderlyIDMousePressed(evt);
            }
        });
        visitElderlyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitElderlyIDActionPerformed(evt);
            }
        });
        visitElderlyID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                visitElderlyIDKeyTyped(evt);
            }
        });
        personalVisitInfoBG.add(visitElderlyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, 40));

        visitVisitorID.setBackground(new java.awt.Color(231, 228, 228));
        visitVisitorID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitVisitorID.setForeground(new java.awt.Color(107, 132, 22));
        visitVisitorID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitVisitorID.setBorder(null);
        visitVisitorID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitVisitorIDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitVisitorIDMousePressed(evt);
            }
        });
        visitVisitorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitVisitorIDActionPerformed(evt);
            }
        });
        visitVisitorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                visitVisitorIDKeyTyped(evt);
            }
        });
        personalVisitInfoBG.add(visitVisitorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 40));

        visitorVisitTime.setBackground(new java.awt.Color(231, 228, 228));
        visitorVisitTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitorVisitTime.setForeground(new java.awt.Color(107, 132, 22));
        visitorVisitTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visitorVisitTime.setBorder(null);
        visitorVisitTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitorVisitTimeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorVisitTimeMousePressed(evt);
            }
        });
        visitorVisitTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorVisitTimeActionPerformed(evt);
            }
        });
        personalVisitInfoBG.add(visitorVisitTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 210, 40));

        updateDateButton.setBackground(new java.awt.Color(176, 212, 55));
        updateDateButton.setFont(new java.awt.Font("Verdana Pro Black", 1, 18)); // NOI18N
        updateDateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateDateButton.setText("UPDATE DATE");
        updateDateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDateButtonActionPerformed(evt);
            }
        });
        personalVisitInfoBG.add(updateDateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 210, 40));

        visitorAdmitTimeText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorAdmitTimeText.setForeground(new java.awt.Color(107, 132, 22));
        visitorAdmitTimeText.setText("Visit Time*");
        visitorAdmitTimeText.setFocusable(false);
        personalVisitInfoBG.add(visitorAdmitTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 110, 20));

        elderlyIDText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        elderlyIDText.setForeground(new java.awt.Color(107, 132, 22));
        elderlyIDText.setText("Assign to ElderlyID*");
        elderlyIDText.setFocusable(false);
        personalVisitInfoBG.add(elderlyIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 130, 20));

        visitVisitorIDText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitVisitorIDText.setForeground(new java.awt.Color(107, 132, 22));
        visitVisitorIDText.setText("Assign to VisitorID*");
        visitVisitorIDText.setFocusable(false);
        personalVisitInfoBG.add(visitVisitorIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, 20));

        visitorAdmitDateText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        visitorAdmitDateText.setForeground(new java.awt.Color(107, 132, 22));
        visitorAdmitDateText.setText("Visit Date*");
        visitorAdmitDateText.setFocusable(false);
        personalVisitInfoBG.add(visitorAdmitDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 110, 20));

        backButton.setBackground(new java.awt.Color(176, 212, 55));
        backButton.setFont(new java.awt.Font("Verdana Pro Black", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("GO BACK");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        personalVisitInfoBG.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 210, 40));

        dateInfoText.setFont(new java.awt.Font("Verdana Pro Black", 1, 18)); // NOI18N
        dateInfoText.setForeground(new java.awt.Color(183, 216, 72));
        dateInfoText.setText("DATE OF VISIT");
        dateInfoText.setFocusable(false);
        personalVisitInfoBG.add(dateInfoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 170, 20));

        getContentPane().add(personalVisitInfoBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 840, 170));

        visitorBackground.setForeground(new java.awt.Color(129, 159, 29));
        visitorBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboardBackground.png"))); // NOI18N
        visitorBackground.setText("jLabel1");
        visitorBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 159, 29), 10, true));
        visitorBackground.setPreferredSize(new java.awt.Dimension(1020, 570));
        getContentPane().add(visitorBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        visitorLastTextField.setFocusable(true);
        visitorFirstTextField.setFocusable(true);
        visitorMiddleTextField.setFocusable(true);
        visitorSuffix.setFocusable(true);
        visitorGender.setFocusable(true);
        visitorBirthdate.setFocusable(true);
        visitorContact.setFocusable(true);
        visitorEmail.setFocusable(true);
        visitorStreet.setFocusable(true);
        visitorBrgy.setFocusable(true);
        visitorCity.setFocusable(true);
        visitorProvince.setFocusable(true);
        visitorVisitDate.setFocusable(true);
        visitorVisitTime.setFocusable(true);
        visitVisitorID.setFocusable(true);
        visitElderlyID.setFocusable(true);
        visitorID.setFocusable(true);
        visitorRelationship.setFocusable(true);
    }//GEN-LAST:event_formMouseEntered

    private void minimizeLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLogoMouseClicked
        this.setExtendedState(VisitorUpdate.ICONIFIED);
    }//GEN-LAST:event_minimizeLogoMouseClicked

    private void visitorLastTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorLastTextFieldMousePressed
        if(visitorLastTextField.getText().equals("Last Name")){
            visitorLastTextField.setText("");
            visitorLastTextField.setFocusable(true);
        }
    }//GEN-LAST:event_visitorLastTextFieldMousePressed

    private void visitorLastTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorLastTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorLastTextFieldActionPerformed

    private void visitorFirstTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorFirstTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorFirstTextFieldMouseClicked

    private void visitorFirstTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorFirstTextFieldMousePressed
        if(visitorFirstTextField.getText().equals("First Name")){
            visitorFirstTextField.setText("");
            visitorFirstTextField.setFocusable(true);
        }
    }//GEN-LAST:event_visitorFirstTextFieldMousePressed

    private void visitorFirstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorFirstTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorFirstTextFieldActionPerformed

    private void visitorMiddleTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorMiddleTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorMiddleTextFieldMouseClicked

    private void visitorMiddleTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorMiddleTextFieldMousePressed
        if(visitorMiddleTextField.getText().equals("Middle Name")){
            visitorMiddleTextField.setText("");
            visitorMiddleTextField.setFocusable(true);
        }
    }//GEN-LAST:event_visitorMiddleTextFieldMousePressed

    private void visitorMiddleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorMiddleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorMiddleTextFieldActionPerformed

    private void visitorBrgyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorBrgyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorBrgyMouseClicked

    private void visitorBrgyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorBrgyMousePressed
        if(visitorBrgy.getText().equals("Barangay")){
            visitorBrgy.setText("");
            visitorBrgy.setFocusable(true);
        }
    }//GEN-LAST:event_visitorBrgyMousePressed

    private void visitorBrgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorBrgyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorBrgyActionPerformed

    private void visitorCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorCityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorCityMouseClicked

    private void visitorCityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorCityMousePressed
        if(visitorCity.getText().equals("City")){
            visitorCity.setText("");
            visitorCity.setFocusable(true);
        }
    }//GEN-LAST:event_visitorCityMousePressed

    private void visitorCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorCityActionPerformed

    private void visitorProvinceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorProvinceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorProvinceMouseClicked

    private void visitorProvinceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorProvinceMousePressed
        if(visitorProvince.getText().equals("Province")){
            visitorProvince.setText("");
            visitorProvince.setFocusable(true);
        }
    }//GEN-LAST:event_visitorProvinceMousePressed

    private void visitorProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorProvinceActionPerformed

    private void visitorSuffixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorSuffixMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorSuffixMouseClicked

    private void visitorSuffixMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorSuffixMousePressed
        if(visitorSuffix.getText().equals("Suffix Name")){
            visitorSuffix.setText("");
            visitorSuffix.setFocusable(true);
        }
    }//GEN-LAST:event_visitorSuffixMousePressed

    private void visitorSuffixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorSuffixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorSuffixActionPerformed

    private void visitorGenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorGenderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorGenderMouseClicked

    private void visitorGenderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorGenderMousePressed
        if(visitorGender.getText().equals("Gender")){
            visitorGender.setText("");
            visitorGender.setFocusable(true);
        }
    }//GEN-LAST:event_visitorGenderMousePressed

    private void visitorGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorGenderActionPerformed

    private void visitorContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorContactMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorContactMouseClicked

    private void visitorContactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorContactMousePressed
        if(visitorContact.getText().equals("Contact Number")){
            visitorContact.setText("");
            visitorContact.setFocusable(true);
        }
    }//GEN-LAST:event_visitorContactMousePressed

    private void visitorContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorContactActionPerformed

    private void visitorContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visitorContactKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_visitorContactKeyTyped

    private void visitorEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorEmailMouseClicked

    private void visitorEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorEmailMousePressed
        if(visitorEmail.getText().equals("Email Address")){
            visitorEmail.setText("");
            visitorEmail.setFocusable(true);
        }
    }//GEN-LAST:event_visitorEmailMousePressed

    private void visitorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorEmailActionPerformed

    private void visitorStreetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorStreetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorStreetMouseClicked

    private void visitorStreetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorStreetMousePressed
        if(visitorStreet.getText().equals("Street")){
            visitorStreet.setText("");
            visitorStreet.setFocusable(true);
        }
    }//GEN-LAST:event_visitorStreetMousePressed

    private void visitorStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorStreetActionPerformed

    private void updateVisitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVisitorButtonActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DatabaseConnection.DB_CONNECTION,"root","root");
            String sql = "UPDATE visitor SET LastName = ?, FirstName = ?, MiddleName = ?, SuffixName = ?, Gender = ?, BirthDate = ?, ContactNo = ?, Email = ?, Street = ?, Barangay = ?, CityMunicipality = ?, Province = ?, Relationship = ? WHERE VisitorID = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            String lastName = visitorLastTextField.getText();
            pst.setString(1, lastName);
            String firstName = visitorFirstTextField.getText();
            pst.setString(2, firstName);
            String middleName = visitorMiddleTextField.getText();
            pst.setString(3, middleName);
            String suffixName = visitorSuffix.getText();
            pst.setString(4, suffixName);
            String gender = visitorGender.getText();
            pst.setString(5, gender);
            String email = visitorEmail.getText();
            pst.setString(8, email);
            String street = visitorStreet.getText();
            pst.setString(9, street);
            String brgy = visitorBrgy.getText();
            pst.setString(10, brgy);
            String city = visitorCity.getText();
            pst.setString(11, city);
            String province = visitorProvince.getText();
            pst.setString(12, province);
            String relationship = visitorRelationship.getText();
            pst.setString(13, relationship);
            int visitorid = Integer.parseInt(visitorID.getText());
            pst.setInt(14, visitorid);
            
            //Date
            DateTimeFormatter formatter, time;
                    formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDate birthDate = visitorBirthdate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String formattedBirthDate = birthDate.format(formatter);
            pst.setString(6, formattedBirthDate);

            //Contact Number
            String contactNo = visitorContact.getText();
            
            if(contactNo.length() == 11){
                long ContactNo = Long.parseLong(contactNo);
                pst.setString(7, Long.toString(ContactNo));

            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Contact Number");
            }
            
            int result = pst.executeUpdate();
            
            if(result == 1){
                JOptionPane.showMessageDialog(this, "Visitor Updated Successfully!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Record failed to update!");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Connection Error!" + e.getMessage());
        }
    }//GEN-LAST:event_updateVisitorButtonActionPerformed

    private void visitorRelationshipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorRelationshipMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorRelationshipMouseClicked

    private void visitorRelationshipMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorRelationshipMousePressed
        if(visitorRelationship.getText().equals("Relationship to Elderly")){
            visitorRelationship.setText("");
            visitorRelationship.setFocusable(true);
        }
    }//GEN-LAST:event_visitorRelationshipMousePressed

    private void visitorRelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorRelationshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorRelationshipActionPerformed

    private void visitorVisitDateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorVisitDateMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorVisitDateMousePressed

    private void visitElderlyIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitElderlyIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitElderlyIDMouseClicked

    private void visitElderlyIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitElderlyIDMousePressed
        if(visitElderlyID.getText().equals("Assign to Elderly ID")){
            visitElderlyID.setText("");
            visitElderlyID.setFocusable(true);
        }
    }//GEN-LAST:event_visitElderlyIDMousePressed

    private void visitElderlyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitElderlyIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitElderlyIDActionPerformed

    private void visitElderlyIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visitElderlyIDKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_visitElderlyIDKeyTyped

    private void visitVisitorIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitVisitorIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitVisitorIDMouseClicked

    private void visitVisitorIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitVisitorIDMousePressed
        if(visitVisitorID.getText().equals("Assign to Visitor ID")){
            visitVisitorID.setText("");
            visitVisitorID.setFocusable(true);
        }
    }//GEN-LAST:event_visitVisitorIDMousePressed

    private void visitVisitorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitVisitorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitVisitorIDActionPerformed

    private void visitVisitorIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visitVisitorIDKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_visitVisitorIDKeyTyped

    private void visitorVisitTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorVisitTimeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorVisitTimeMouseClicked

    private void visitorVisitTimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorVisitTimeMousePressed
        if(visitorVisitTime.getText().equals("Visit Time")){
            visitorVisitTime.setText("");
            visitorVisitTime.setFocusable(true);
        }
    }//GEN-LAST:event_visitorVisitTimeMousePressed

    private void visitorVisitTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorVisitTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorVisitTimeActionPerformed

    private void updateDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDateButtonActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DatabaseConnection.DB_CONNECTION,"root","root");
            String sql = "UPDATE dateofvisit SET VisitorID = ?, ElderlyID = ?, VisitDate =?, VisitTime = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            int visitorid = Integer.parseInt(visitVisitorID.getText());
            pst.setInt(1, visitorid);
            int elderlyid = Integer.parseInt(visitElderlyID.getText());
            pst.setInt(2, elderlyid);
            String visitTime = visitorVisitTime.getText();
            pst.setString(4, visitTime);

            //Date
            DateTimeFormatter formatter;
            formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");

            LocalDate visitDate = visitorVisitDate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String formattedVisitDate = visitDate.format(formatter);
            pst.setString(3, formattedVisitDate);

            int result = pst.executeUpdate();

            if(result == 1){
                JOptionPane.showMessageDialog(this, "Date Updated Successfully!");
                visitorVisitTime.setText("");
                VisitorDetails visitorDetails = new VisitorDetails();
                visitorDetails.setVisible(true);
                this.setVisible(false);
                pst.close();
                con.close();
            }
            else{
                JOptionPane.showMessageDialog(this, "Record failed to update!");
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Connection Error!" + e.getMessage());
        }

        VisitorDetails visitorDetails = new VisitorDetails();
        String database = "SELECT visitor.VisitorID, visitor.FirstName, visitor.MiddleName, visitor.LastName, visitor.SuffixName, visitor.Gender, visitor.BirthDate, visitor.Relationship, visitor.ContactNo, visitor.Email, visitor.Street, visitor.Barangay, visitor.CityMunicipality, visitor.Province FROM visitor";
        try{
            Connection con = DriverManager.getConnection(DatabaseConnection.DB_CONNECTION,"root","root");
            PreparedStatement pst = con.prepareStatement(database);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel table = (DefaultTableModel) visitorDetails.getVisitorTable().getModel();
            table.setRowCount(0);

            while(rs.next()){
                Object[] row = {
                    rs.getInt("visitor.VisitorID"),
                    rs.getString("visitor.FirstName"),
                    rs.getString("visitor.MiddleName"),
                    rs.getString("visitor.LastName"),
                    rs.getString("visitor.SuffixName"),
                    rs.getString("visitor.Gender"),
                    rs.getObject("visitor.BirthDate"),
                    rs.getString("visitor.Relationship"),
                    rs.getLong("visitor.ContactNo"),
                    rs.getString("visitor.Email"),
                    rs.getString("visitor.Street"),
                    rs.getString("visitor.Barangay"),
                    rs.getString("visitor.CityMunicipality"),
                    rs.getString("visitor.Province"),
                };
                table.addRow(row);
            }
            visitorDetails.getVisitorTable().setModel(table);
            visitorDetails.setVisible(true);
            this.setVisible(false);
            rs.close();
            pst.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Connection Error!" + e.getMessage());
        }
    }//GEN-LAST:event_updateDateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        VisitorDetails visitorDetails = new VisitorDetails();
        String database = "SELECT visitor.VisitorID, visitor.FirstName, visitor.MiddleName, visitor.LastName, visitor.SuffixName, visitor.Gender, visitor.BirthDate, visitor.Relationship, visitor.ContactNo, visitor.Email, visitor.Street, visitor.Barangay, visitor.CityMunicipality, visitor.Province FROM visitor";
        try{
            Connection con = DriverManager.getConnection(DatabaseConnection.DB_CONNECTION,"root","root");
            PreparedStatement pst = con.prepareStatement(database);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel table = (DefaultTableModel) visitorDetails.getVisitorTable().getModel();
            table.setRowCount(0);

            while(rs.next()){
                Object[] row = {
                    rs.getInt("visitor.VisitorID"),
                    rs.getString("visitor.FirstName"),
                    rs.getString("visitor.MiddleName"),
                    rs.getString("visitor.LastName"),
                    rs.getString("visitor.SuffixName"),
                    rs.getString("visitor.Gender"),
                    rs.getObject("visitor.BirthDate"),
                    rs.getString("visitor.Relationship"),
                    rs.getLong("visitor.ContactNo"),
                    rs.getString("visitor.Email"),
                    rs.getString("visitor.Street"),
                    rs.getString("visitor.Barangay"),
                    rs.getString("visitor.CityMunicipality"),
                    rs.getString("visitor.Province"),
                };
                table.addRow(row);
            }
            visitorDetails.getVisitorTable().setModel(table);
            visitorDetails.setVisible(true);
            this.setVisible(false);
            rs.close();
            pst.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Connection Error!" + e.getMessage());
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void visitorIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorIDMouseClicked

    private void visitorIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorIDMousePressed
        if(visitorID.getText().equals("Visitor ID")){
            visitorID.setText("");
            visitorID.setFocusable(true);
        }
    }//GEN-LAST:event_visitorIDMousePressed

    private void visitorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorIDActionPerformed

    private void visitorIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visitorIDKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_visitorIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitorUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dateInfoText;
    private javax.swing.JLabel elderlyIDText;
    private javax.swing.JLabel minimizeLogo;
    private javax.swing.JPanel personalInfoBG;
    private javax.swing.JLabel personalInfoText;
    private javax.swing.JPanel personalVisitInfoBG;
    private javax.swing.JButton updateDateButton;
    private javax.swing.JButton updateVisitorButton;
    private javax.swing.JTextField visitElderlyID;
    private javax.swing.JTextField visitVisitorID;
    private javax.swing.JLabel visitVisitorIDText;
    private javax.swing.JLabel visitorAddressText;
    private javax.swing.JLabel visitorAdmitDateText;
    private javax.swing.JLabel visitorAdmitTimeText;
    private javax.swing.JLabel visitorBackground;
    private com.toedter.calendar.JDateChooser visitorBirthdate;
    private javax.swing.JLabel visitorBirthdateText;
    private javax.swing.JTextField visitorBrgy;
    private javax.swing.JLabel visitorBrgyText;
    private javax.swing.JTextField visitorCity;
    private javax.swing.JLabel visitorCityText;
    private javax.swing.JTextField visitorContact;
    private javax.swing.JLabel visitorContactNoText;
    private javax.swing.JTextField visitorEmail;
    private javax.swing.JLabel visitorEmailText;
    private javax.swing.JLabel visitorFirstText;
    private javax.swing.JTextField visitorFirstTextField;
    private javax.swing.JTextField visitorGender;
    private javax.swing.JLabel visitorGenderText;
    private javax.swing.JTextField visitorID;
    private javax.swing.JLabel visitorIDText;
    private javax.swing.JLabel visitorInformationText;
    private javax.swing.JLabel visitorLastName;
    private javax.swing.JTextField visitorLastTextField;
    private javax.swing.JLabel visitorMiddleText;
    private javax.swing.JTextField visitorMiddleTextField;
    private javax.swing.JTextField visitorProvince;
    private javax.swing.JLabel visitorProvinceText;
    private javax.swing.JTextField visitorRelationship;
    private javax.swing.JLabel visitorRelationshipText;
    private javax.swing.JTextField visitorStreet;
    private javax.swing.JLabel visitorStreetText;
    private javax.swing.JTextField visitorSuffix;
    private javax.swing.JLabel visitorSuffixText;
    private com.toedter.calendar.JDateChooser visitorVisitDate;
    private javax.swing.JTextField visitorVisitTime;
    // End of variables declaration//GEN-END:variables
}
